import { useState } from 'react';
import { ArrowRight, CalendarDays, Check, ChevronDown, Clock3, Dumbbell, Instagram, Mail, MapPin, Menu, Phone, Play, Sparkles, Waves, X } from 'lucide-react';

const images = { hero: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1800&q=85', spa: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1400&q=85', fitness: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1400&q=85', pool: 'https://images.unsplash.com/photo-1519315901367-f34ff9154487?auto=format&fit=crop&w=1400&q=85', facial: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80', massage: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=900&q=80', body: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80', wellness: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=900&q=80', gym: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80', recovery: 'https://images.unsplash.com/photo-1552693673-1bf958298935?auto=format&fit=crop&w=900&q=80' };
const services = [['Signature Facial','A relaxing facial experience designed to refresh and restore the skin.', '₦25,000', images.facial], ['Deep Relax Massage','A calming full-body massage concept created for relaxation.', '₦35,000', images.massage], ['Glow Body Treatment','A luxurious body-care experience designed to leave skin feeling refreshed.', '₦35,000', images.body], ['Wellness Session','A personalized wellness experience focused on relaxation and balance.', '₦25,000', images.wellness], ['Fitness Training','A modern training experience for strength, movement and confidence.', '₦45,000', images.gym], ['Pool & Recovery','A relaxing pool and recovery experience for movement and reset.', '₦30,000', images.recovery]];
const plans = [{ name: 'Essential', price: '₦30,000', features: ['Gym access','2 sample classes','Recovery area'] }, { name: 'Wellness', price: '₦50,000', features: ['Gym access','6 sample classes','Wellness session','Pool access'], featured: true }, { name: 'Premium', price: '₦75,000', features: ['Gym access','Unlimited sample classes','1:1 training option','Pool & recovery'] }];

function App() {
  const [menu, setMenu] = useState(false); const [sent, setSent] = useState(false); const [gallery, setGallery] = useState('All'); const [detail, setDetail] = useState<string | null>(null);
  const scroll = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenu(false); };
  const submit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); setSent(true); };
  return <div className="site">
    <div className="demo-ribbon">DEMO WEBSITE / CONCEPT <span>•</span> NOT OFFICIAL</div>
    <header className="nav"><button className="brand" onClick={() => scroll('home')}><span>DELPORE</span><small>SPA & WELLNESS</small></button><nav>{['Home','About','Services','Wellness','Fitness','Membership','Contact'].map(x => <button key={x} onClick={() => scroll(x.toLowerCase())}>{x}</button>)}</nav><button className="book" onClick={() => scroll('booking')}>Book Now <ArrowRight size={16}/></button><button className="hamb" aria-label="Open menu" onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></header>
    {menu && <div className="mobile-menu">{['Home','About','Services','Wellness','Fitness','Membership','Contact'].map(x => <button key={x} onClick={() => scroll(x.toLowerCase())}>{x}</button>)}<button className="mobile-book" onClick={() => scroll('booking')}>Book Now <ArrowRight size={17}/></button></div>}
    <main>
      <section id="home" className="hero" style={{ backgroundImage: `linear-gradient(90deg,rgba(11,24,25,.78),rgba(11,24,25,.35)),url(${images.hero})` }}><div className="hero-copy"><span className="eyebrow">WEBSITE CONCEPT • DEMO</span><h1>Your Space to <em>Relax, Renew</em> & Reconnect.</h1><p>A modern approach to beauty, wellness and fitness — designed around you.</p><div className="actions"><button className="primary" onClick={() => scroll('booking')}>Book a Visit <ArrowRight size={17}/></button><button className="ghost" onClick={() => scroll('services')}>Explore Services</button></div></div><div className="hero-note"><Sparkles size={17}/> Sample experience • Fictional concept</div></section>
      <section id="about" className="section about"><div className="section-label">ABOUT THE CONCEPT</div><div className="about-grid"><div><h2>Wellness, reimagined for <em>you.</em></h2></div><div><p>This fictional concept brings beauty, spa treatments, wellness, fitness and relaxation into one refined digital experience.</p><p className="muted">The copy, claims and figures on this page are sample content created for a sales presentation and can be replaced with verified client information later.</p><span className="sample-pill">SAMPLE CONTENT — TO BE REPLACED WITH CLIENT INFORMATION</span></div></div><div className="stats"><div><b>10+</b><span>Wellness Experiences</span></div><div><b>5★</b><span>Demo Experience Rating</span></div><div><b>100%</b><span>Relaxation Focus</span></div></div></section>
      <section id="services" className="section services"><div className="section-head"><div><div className="section-label">THE MENU</div><h2>Designed for your <em>best self.</em></h2></div><p>Premium sample experiences spanning beauty, spa, wellness and fitness.</p></div><div className="service-grid">{services.map(([name, desc, price, img]) => <article className="service-card" key={name}><img src={img} alt="Generic demo wellness imagery" loading="lazy"/><div className="service-body"><span className="demo-price">DEMO PRICE</span><h3>{name}</h3><p>{desc}</p><div className="service-foot"><strong>{price}</strong><button onClick={() => setDetail(name)}>View Details <ArrowRight size={15}/></button></div></div></article>)}</div></section>
      <section id="wellness" className="experience" style={{ backgroundImage: `linear-gradient(rgba(13,29,28,.55),rgba(13,29,28,.78)),url(${images.spa})` }}><div className="experience-copy"><div className="section-label light">SPA EXPERIENCE • DEMO</div><h2>Leave the Outside <em>World Behind.</em></h2><p>A cinematic sample of how a premium wellness story could unfold online.</p></div><div className="experience-cards">{[['Relax','Slow down and breathe.'],['Restore','Give your body the attention it deserves.'],['Glow','Leave feeling refreshed and confident.']].map(([a,b],i)=><div key={a} className="experience-card"><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></div>)}</div></section>
      <section id="fitness" className="split"><div className="split-img" style={{ backgroundImage: `url(${images.fitness})` }}><span className="image-tag">DEMO IMAGE</span></div><div className="split-copy"><div className="section-label">FITNESS • CONCEPT</div><h2>Stronger <em>Starts Here.</em></h2><p>A modern fitness experience designed to balance movement with the restorative side of wellness.</p><ul><li><Dumbbell/> Gym equipment imagery</li><li><Sparkles/> Personal training concept</li><li><Play/> Fitness classes</li><li><Check/> Wellness coaching</li></ul><div className="mini-stats"><div><b>20+</b><span>Demo Workouts</span></div><div><b>12</b><span>Sample Classes</span></div><div><b>1:1</b><span>Training Options</span></div></div><button className="primary" onClick={() => scroll('membership')}>Explore Fitness <ArrowRight size={17}/></button></div></section>
      <section className="pool" style={{ backgroundImage: `linear-gradient(90deg,rgba(5,25,28,.76),rgba(5,25,28,.25)),url(${images.pool})` }}><div><div className="section-label light">POOL • DEMO EXPERIENCE</div><h2>Make Time <em>for You.</em></h2><p>A calm space to move, unwind and recharge.</p><button className="ghost light-btn" onClick={() => setDetail('Pool & Recovery')}>Discover the Pool <ArrowRight size={17}/></button></div></section>
      <section id="membership" className="section membership"><div className="section-head center"><div><div className="section-label">MEMBERSHIP CONCEPT</div><h2>Choose your <em>ritual.</em></h2><p>All plans and pricing below are fictional examples for this prototype.</p></div></div><div className="plans">{plans.map(plan=><article className={`plan ${plan.featured ? 'featured' : ''}`} key={plan.name}>{plan.featured && <span className="popular">DEMO FAVOURITE</span>}<span className="plan-name">{plan.name}</span><h3>{plan.price}</h3><small>DEMO PRICE / MONTH</small><ul>{plan.features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><button onClick={() => scroll('booking')}>Request Info <ArrowRight size={15}/></button></article>)}</div></section>
      <section id="booking" className="booking section"><div className="booking-intro"><div className="section-label">BOOKING EXPERIENCE</div><h2>Make space for <em>you.</em></h2><p>Interactive prototype form — no real appointment is created or sent.</p><div className="booking-points"><span><CalendarDays/> Flexible requests</span><span><Clock3/> Preferred time</span><span><Phone/> Demo contact flow</span></div></div><div className="form-wrap">{sent ? <div className="success"><div className="success-icon"><Check/></div><h3>Request received — demo only.</h3><p>Thank you! This is a demo booking form. In a real client website, this would connect to the business's booking system.</p><button className="primary" onClick={() => setSent(false)}>Send Another Request</button></div> : <form onSubmit={submit}><div className="form-grid"><label>Full Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>Phone<input required type="tel" placeholder="+234 ..."/></label><label>Service<select required defaultValue=""><option value="" disabled>Select a demo service</option>{services.map(s=><option key={s[0]}>{s[0]}</option>)}</select></label><label>Preferred Date<input required type="date"/></label><label>Preferred Time<input required type="time"/></label><label className="full">Message<textarea placeholder="Tell us what you are looking for..."/></label></div><button className="primary full-btn">Request Appointment <ArrowRight size={17}/></button></form>}</div></section>
      <section className="section testimonials"><div className="section-head center"><div><div className="section-label">SOCIAL PROOF • SAMPLE</div><h2>Words from our <em>demo guests.</em></h2></div></div><div className="quotes"><blockquote><span>SAMPLE TESTIMONIAL</span><p>“Beautiful concept and such a relaxing atmosphere.”</p><footer>— Demo Client</footer></blockquote><blockquote><span>SAMPLE TESTIMONIAL</span><p>“Exactly the kind of experience I would expect from a premium wellness brand.”</p><footer>— Demo Guest</footer></blockquote></div></section>
      <section className="section gallery"><div className="section-head"><div><div className="section-label">VISUAL DIRECTION</div><h2>A glimpse of the <em>experience.</em></h2></div><div className="filters">{['All','Spa','Beauty','Fitness','Pool','Wellness'].map(x=><button className={gallery===x?'active':''} onClick={()=>setGallery(x)} key={x}>{x}</button>)}</div></div><div className="gallery-grid">{[{c:'Spa',i:images.spa},{c:'Beauty',i:images.facial},{c:'Fitness',i:images.fitness},{c:'Pool',i:images.pool},{c:'Wellness',i:images.wellness},{c:'Fitness',i:images.gym}].filter(x=>gallery==='All'||x.c===gallery).map((x,i)=><div className="gallery-item" key={x.i}><img src={x.i} alt={`${x.c} demo concept`} loading="lazy"/><span>{x.c} • DEMO</span></div>)}</div></section>
      <section id="contact" className="contact section"><div><div className="section-label">CONTACT • DEMO</div><h2>Let's create something <em>remarkable.</em></h2><p>This is fictional contact information for presentation purposes only.</p></div><div className="contact-card"><span className="sample-pill">DEMO CONTACT INFORMATION</span><h3>Demo Wellness Studio</h3><p><MapPin/>24 Serenity Avenue<br/>Lagos, Nigeria</p><p><Phone/>+234 800 000 0000</p><p><Mail/>hello@example-demo.com</p></div></section>
      <section className="cta"><div className="section-label light">THE NEXT STEP</div><h2>Ready to Create Your Own <em>Digital Experience?</em></h2><p>This website is a concept demonstrating how a modern beauty, spa and fitness brand could present itself online.</p><button className="primary" onClick={() => setDetail('Request a Custom Website')}>Request a Custom Website <ArrowRight size={17}/></button></section>
    </main>
    <footer className="footer"><div><div className="footer-brand">DELPORE <span>SPA & WELLNESS</span></div><p>Website Concept by Vanessa</p></div><div className="footer-links">{['Home','About','Services','Wellness','Fitness','Membership','Contact'].map(x=><button key={x} onClick={()=>scroll(x.toLowerCase())}>{x}</button>)}</div><div className="socials"><Instagram/><Mail/><Phone/></div><div className="footer-demo">DEMO WEBSITE — NOT THE OFFICIAL WEBSITE OF DELPOSH BEAUTY & FITNESS</div></footer>
    {detail && <div className="modal-backdrop" onClick={()=>setDetail(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setDetail(null)}><X/></button><span className="sample-pill">DEMO INTERACTION</span><h3>{detail}</h3><p>This is a prototype interaction for the sales presentation. In a finished client website, this area could contain verified service details, availability, booking or enquiry actions.</p><button className="primary" onClick={()=>{setDetail(null);scroll('booking')}}>Continue to Demo Booking <ArrowRight size={17}/></button></div></div>}
  </div>;
}
export default App;